version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: library_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  redis:
    image: redis:latest
    container_name: book-cache
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: library_api
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - REDIS_URL=redis

  prism-mock:
    image: stoplight/prism:5
    container_name: library_prism_mock
    ports:
      - "4010:4010"
    volumes:
      - ./openapi.yaml:/usr/src/api/openapi.yaml:ro
    command: mock -m false -h 0.0.0.0 /usr/src/api/openapi.yaml

volumes:
  mongo_data: